// AssetsReducer
export const GET_ASSETS = "GET_ASSETS";
export const ERROR_GET_ASSETS = "ERROR_GET_ASSETS";

// LCUconnectorReducer
export const LCU_CONNECT = "LCU_CONNECT";
export const LCU_DISCONNECT = "LCU_DISCONNECT";
export const CHAMPSELECT_CHANGE = "CHAMPSELECT_CHANGE";
export const GAMESESSION_CHANGE = "GAMESESSION_CHANGE";
export const LOBBY_CHANGE = "LOBBY_CHANGE";

// IngameReducer
export const UPDATE_GAMEINFO = "UPDATE_GAMEINFO";
export const UPDATE_ADVISE = "UPDATE_ADVISE";
export const UPDATE_TIMER = "UPDATE_TIMER";
export const UPDATE_LAST_EVENT = "UPDATE_LAST_EVENT";
export const UPDATE_EVENTS_NOTIFIED = "UPDATE_EVENTS_NOTIFIED";
export const UPDATE_INGAME_STATE = "UPDATE_INGAME_STATE";
export const CLEAN_INGAME_REDUCER = "CLEAN_INGAME_REDUCER";

// configReducer
export const UPDATE_CONFIG = "UPDATE_CONFIG";
