export const LCU_CONNECT = "LCU_CONNECT";
export const LCU_DISCONNECT = "LCU_DISCONNECT";
export const LOBBY_CHANGE = "LOBBY_CHANGE";
export const CHAMPSELECT_CHANGE = "CHAMPSELECT_CHANGE";
export const GAMESESSION_CHANGE = "GAMESESSION_CHANGE";
