export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const INITIALIZE_BUILD_APPLIED_EVENT = "INITIALIZE_BUILD_APPLIED_EVENT";
export const INITIALIZE_BUILD_FAILED_EVENT = "INITIALIZE_BUILD_FAILED_EVENT";
