export const UPDATE_GAMEINFO = "UPDATE_GAMEINFO";
export const CLEAN_GAMEINFO = "CLEAN_GAMEINFO";
export const INITIALIZE_CURRENT_GAME_LISTENER =
  "INITIALIZE_CURRENT_GAME_LISTENER";
export const STOP_FETCHING_CURRENT_GAME = "STOP_FETCHING_CURRENT_GAME";
export const START_FETCHING_CURRENT_GAME = "START_FETCHING_CURRENT_GAME";
